fix: [ND-7819] bug fix refinements
ninoxdb/ninox-dev-cli pull request #28
Opened 2024-06-20 04:53 UTC by saqibarfeen

Bug fixes:
- Reports and Views were downloaded separately, failing when there were many e.g 200 views because all we downloaded parallel with Promise.all. Changed to use bulk download API for Reports and Views
-  order and seq fields are made optional, due to cases found where these fields were missing in views
-  ~prevented js-yaml dump from adding line-breaks in multi-line strings by passing `{lineWidth: -1}`~
- Migrated from `js-yaml` to `yaml` as js-yaml was not printing the tab characters in scripts, vs yaml , which automatically converts tabs to spaces when printing
- Table fields were shown with keys of their fieldId e.g A,B,C . Changed it to field.caption (which is also unique) for better readability

UX improvements:
- Added spinner in all commands
- Printed Database list in a table
- Bumped version to 0.1.2

---

Related changes in Ninox Server: https://github.com/ninoxdb/ninox/pull/2489

2024-06-21 13:17 UTC, Hamcker submitted a review, later dismissed
lgtm, please read my prev comment.

2024-06-24 14:33 UTC, Hamcker submitted a review, later dismissed

2024-06-26 10:51 UTC, Hamcker submitted a review, later dismissed

2024-06-26 10:56 UTC, Hamcker submitted a review, later dismissed

2024-06-27 11:46 UTC, bilguungantulga requested changes
left some minor regards

2024-06-27 13:59 UTC, bilguungantulga approved these changes

2024-06-27 14:02 UTC, Hamcker approved these changes

2024-06-27 14:03 UTC, merged