[ND-8238] ninox cli with test
ninoxdb/ninox-dev-cli pull request #3
Opened 2024-05-07 14:04 UTC by saqibarfeen

This is the ninox cli , that is the first releaseable version. (The POC can be found [here](https://github.com/ninoxdb/ninox-dev-cli/tree/feat/nd-7872-ninoxsdk-poc))

It is also different from the POC in that, the POC was a adhoc project, and the cli was built on commander framework.
Now, it is built on top of `oclif`  which is a Nodejs CLI framework, built and maintained by salesforce.
The salesforce cli and heroku cli are made on oclif framework. 

It has tests for each of the commands:
1. init
2. list
3. download
4. upload

~The unit tests are not written yet. I have to separate business logic, service and API client layers.~
~Then I will think about writing tests for each layer e.g service, client and then finally may be the helper utility function.~

The reason to choose OCLIF:
1. Generates documentation (README) automatically (see README.md)
2. Easy extension: New commands and their tests generated automatically via scaffolding e.g
[oclif generate NAME](https://oclif.io/docs/generator_commands/#oclif-generate-name)
[oclif generate command NAME](https://oclif.io/docs/generator_commands/#oclif-generate-command-name)
[oclif generate hook NAME](https://oclif.io/docs/generator_commands/#oclif-generate-hook-name)
3. Easy development e.g new functionality (e.g [interactive commands](https://oclif.io/docs/flexible_taxonomy/#hook-implementation)) added plug-n-play
4. oclif is open-source

#### Update 27. May 2024

Here is the new updated process for the 3 (out of 4) main commands:

1. List Databases
<img width="958" alt="Screenshot 2024-05-27 at 12 06 47" src="https://github.com/ninoxdb/ninox-dev-cli/assets/27664866/3f4dceb8-601d-4205-99b0-1da72a72698b">

3. Download a Database
<img width="957" alt="Screenshot 2024-05-27 at 12 06 22" src="https://github.com/ninoxdb/ninox-dev-cli/assets/27664866/95264148-4561-4364-b448-7f4fc6783e65">

5. Upload a Database
<img width="669" alt="Screenshot 2024-05-27 at 12 06 35" src="https://github.com/ninoxdb/ninox-dev-cli/assets/27664866/3b683790-eac3-448b-9b54-b5ecd609c788">

2024-05-10 08:47 UTC, erroldsilva requested changes

2024-05-14 08:21 UTC, erroldsilva requested changes

2024-05-14 10:33 UTC, osamaninox requested changes

2024-05-14 13:09 UTC, bilguungantulga requested changes
see my comments
[the whole code base need to be formatted]

2024-05-24 12:45 UTC, erroldsilva requested changes

2024-05-27 07:20 UTC, erroldsilva submitted a review, later dismissed

2024-05-27 10:22 UTC, erroldsilva approved these changes

2024-05-27 14:14 UTC, bilguungantulga approved these changes

2024-05-27 14:25 UTC, osamaninox approved these changes

2024-05-27 14:41 UTC, merged